implement retries for externaltask clients and handle failure
remedyMatch/rm-backend pull request #9
Opened 2020-04-10 17:00 UTC by hauptmedia

2020-04-10 22:38 UTC, matusmala commented on src/main/java/io/remedymatch/angebot/process/AngebotExternalTaskClient.java
> +                        externalTaskService.handleFailure(externalTask, "Hello I am an error", "more space for details", retries, 30000);
Eine sprechende Fehlermeldung bitte ;-)

2020-04-10 22:39 UTC, matusmala commented on src/main/java/io/remedymatch/angebot/process/AngebotExternalTaskClient.java
> +                        externalTaskService.handleFailure(externalTask, "Hello I am an error", "more space for details", retries, 30000);
Kannst du bitte auch das Time in Konstante rausextrahieren?

2020-04-10 22:39 UTC, matusmala commented on src/main/java/io/remedymatch/angebot/process/AngebotExternalTaskClient.java
> +        //externalTaskService.handleFailure(externalTask.getId(), "I am a message", "I have more details", 1, 600000);
Brauchen wir diese Kommentare?

2020-04-10 22:41 UTC, matusmala reviewed
Brauchen wir hier eigentlich Retries, wenn wir nur Services aus unseren App aufrufen? Das Task wird doch sicher nicht automatisch committed oder?

2020-04-25 08:11 UTC, matusmala requested changes
Also ich glaube nicht, dass Retry gute idee ist. Wenn sich eine Angebot nicht ablehnen lässt, weil die bereits gelöscht oder in anderem Status liegt, dann sollte der Versuch nicht wiederhollt werden.
@dominikhorn93 die Alternative ? Kein Retry ?

2020-05-05 11:54 UTC, closed without merging

2020-05-05 11:54 UTC, dominikhorn93 commented
Ist in institution_beantragen mit drin